apiVersion: v1
kind: Pod
metadata:
  name: pod-challenge2
  labels:
    description: challenge2
spec:
  containers:
    - name: challenge2-image
      image: roxsross12/k8s_test_web:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "50m"
      ports:
        - containerPort: 80
